/*
 * This file is generated by jOOQ.
 */
package com.example.starter.db.tables.records;


import com.example.starter.db.tables.Greeting;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GreetingRecord extends UpdatableRecordImpl<GreetingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greeting.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>greeting.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>greeting.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greeting.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>greeting.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>greeting.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>greeting.version</code>.
     */
    public void setVersion(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>greeting.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GreetingRecord
     */
    public GreetingRecord() {
        super(Greeting.GREETING);
    }

    /**
     * Create a detached, initialised GreetingRecord
     */
    public GreetingRecord(UUID id, String name, OffsetDateTime createdAt, Integer version) {
        super(Greeting.GREETING);

        setId(id);
        setName(name);
        setCreatedAt(createdAt);
        setVersion(version);
        resetTouchedOnNotNull();
    }
}
