/*
 * This file is generated by jOOQ.
 */
package com.example.starter.db;


import com.example.starter.db.tables.Greeting;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GREETING_CREATED_AT_ID_IDX = Internal.createIndex(DSL.name("greeting_created_at_id_idx"), Greeting.GREETING, new OrderField[] { Greeting.GREETING.CREATED_AT.desc(), Greeting.GREETING.ID.desc() }, false);
}
