/*
 * This file is generated by jOOQ.
 */
package com.example.starter.db;


import com.example.starter.db.tables.Greeting;
import com.example.starter.db.tables.records.GreetingRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GreetingRecord> GREETING_PKEY = Internal.createUniqueKey(Greeting.GREETING, DSL.name("greeting_pkey"), new TableField[] { Greeting.GREETING.ID }, true);
}
