/*
 * This file is generated by jOOQ.
 */
package com.example.starter.db;


import com.example.starter.db.tables.Greeting;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>greeting</code>.
     */
    public static final Greeting GREETING = Greeting.GREETING;
}
