/*
 * This file is generated by jOOQ.
 */
package com.example.starter.db.tables;


import com.example.starter.db.DefaultSchema;
import com.example.starter.db.Indexes;
import com.example.starter.db.Keys;
import com.example.starter.db.tables.records.GreetingRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Greeting extends TableImpl<GreetingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>greeting</code>
     */
    public static final Greeting GREETING = new Greeting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GreetingRecord> getRecordType() {
        return GreetingRecord.class;
    }

    /**
     * The column <code>greeting.id</code>.
     */
    public final TableField<GreetingRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuidv7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>greeting.name</code>.
     */
    public final TableField<GreetingRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>greeting.created_at</code>.
     */
    public final TableField<GreetingRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>greeting.version</code>.
     */
    public final TableField<GreetingRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    private Greeting(Name alias, Table<GreetingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Greeting(Name alias, Table<GreetingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>greeting</code> table reference
     */
    public Greeting(String alias) {
        this(DSL.name(alias), GREETING);
    }

    /**
     * Create an aliased <code>greeting</code> table reference
     */
    public Greeting(Name alias) {
        this(alias, GREETING);
    }

    /**
     * Create a <code>greeting</code> table reference
     */
    public Greeting() {
        this(DSL.name("greeting"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GREETING_CREATED_AT_ID_IDX);
    }

    @Override
    public UniqueKey<GreetingRecord> getPrimaryKey() {
        return Keys.GREETING_PKEY;
    }

    @Override
    public List<Check<GreetingRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("greeting_name_check"), "(((char_length(name) >= 1) AND (char_length(name) <= 100)))", true)
        );
    }

    @Override
    public Greeting as(String alias) {
        return new Greeting(DSL.name(alias), this);
    }

    @Override
    public Greeting as(Name alias) {
        return new Greeting(alias, this);
    }

    @Override
    public Greeting as(Table<?> alias) {
        return new Greeting(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Greeting rename(String name) {
        return new Greeting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Greeting rename(Name name) {
        return new Greeting(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Greeting rename(Table<?> name) {
        return new Greeting(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Greeting where(Condition condition) {
        return new Greeting(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Greeting where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Greeting where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Greeting where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Greeting where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Greeting where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Greeting where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Greeting where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Greeting whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Greeting whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
